language: cpp
os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  global:
    secure: GvgROh8aSriDE1lTsoy1t193dzyFOdPtRFXwXb6+tx1yJijc37dnU9B5rpimH3mtoc0iTpVXrkD1Y+6aqIvN/CRLGWEYmLLwCLXScmQjTPBXWC1htGWlCKvibPdXi0A0qHWMGuXlYgvf2/bcWJidvx06KF/8lSKic+f+LN9X0Uo=

sudo: required

before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi 
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq && sudo apt-get install -qqy automake g++-5 libcppunit-dev valgrind; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install cppunit valgrind; fi

before_script:
- ./bootstrap

script:
- make scrm scrm_dbg
- make unittests
- ./tests/test_binaries.sh
- make algorithmtest

after_success:
- .travis/deploy.sh
