language: cpp
os:
  - linux
  - osx
env:
  global:
    secure: GvgROh8aSriDE1lTsoy1t193dzyFOdPtRFXwXb6+tx1yJijc37dnU9B5rpimH3mtoc0iTpVXrkD1Y+6aqIvN/CRLGWEYmLLwCLXScmQjTPBXWC1htGWlCKvibPdXi0A0qHWMGuXlYgvf2/bcWJidvx06KF/8lSKic+f+LN9X0Uo=
compiler:
- gcc
- clang
script:
- make scrm scrm_dbg
- make unittests
- ./tests/test_binaries.sh
- make algorithmtest
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:dns/gnu; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi 
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qqy automake g++-4.8 libcppunit-dev valgrind; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install llvm cppunit valgrind; fi
- #if [ "$TRAVIS_OS_NAME" == "osx" ] && [ "$CC" == "gcc" ]; then export CXX=g++-4.8; fi
- g++ --version
before_script:
- ./bootstrap
after_success:
- .travis/deploy.sh
